import type { Doctor } from "./types";

const photo = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&crop=faces&w=640&h=640&q=80`;

/**
 * Roster used to seed Supabase (`supabase/seed.sql`) and to serve the app in
 * demo mode. Swap `photo_url` for your own headshots in production.
 */
export const SEED_DOCTORS: Doctor[] = [
  {
    id: "11111111-1111-4111-8111-111111111101",
    slug: "elena-vasquez",
    name: "Elena Vasquez",
    credentials: "MD, FAAFP",
    specialty: "Family Medicine",
    bio: "Elena has spent seventeen years looking after families in the Northlake area — often three generations of the same one. She focuses on preventive care, chronic condition management, and the unglamorous work of catching things early.",
    photo_url: photo("photo-1559839734-2b71ea197ec2"),
    years_experience: 17,
    rating: 4.9,
    reviews_count: 412,
    languages: ["English", "Spanish"],
    education: "Johns Hopkins School of Medicine · Residency at UCSF",
    consultation_fee: 145,
    location: "Northlake Main Clinic · Floor 2",
    working_days: [1, 2, 3, 4, 5],
    start_time: "09:00",
    end_time: "17:00",
    slot_minutes: 30,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111102",
    slug: "rahul-menon",
    name: "Rahul Menon",
    credentials: "MD, FACC",
    specialty: "Cardiology",
    bio: "Board-certified cardiologist with a subspecialty in preventive cardiology and heart failure. Rahul runs the clinic's cardiac imaging program and believes most heart disease is a conversation that should have happened ten years earlier.",
    photo_url: photo("photo-1612349317150-e413f6a5b16d"),
    years_experience: 14,
    rating: 4.8,
    reviews_count: 287,
    languages: ["English", "Hindi", "Malayalam"],
    education: "AIIMS New Delhi · Fellowship at Cleveland Clinic",
    consultation_fee: 225,
    location: "Cardiac Center · Floor 4",
    working_days: [1, 2, 4, 5],
    start_time: "08:00",
    end_time: "16:00",
    slot_minutes: 45,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111103",
    slug: "marcus-bell",
    name: "Marcus Bell",
    credentials: "DO, CAQSM",
    specialty: "Orthopedics & Sports Medicine",
    bio: "Marcus treats everyone from weekend runners to the county's high-school athletic programs. Non-surgical first, with ultrasound-guided injections and a rehab plan you will actually follow.",
    photo_url: photo("photo-1622253692010-333f2da6031d"),
    years_experience: 11,
    rating: 4.9,
    reviews_count: 356,
    languages: ["English"],
    education: "Michigan State COM · Sports Medicine Fellowship, Andrews Institute",
    consultation_fee: 190,
    location: "Sports Medicine Wing · Floor 1",
    working_days: [1, 2, 3, 5, 6],
    start_time: "07:30",
    end_time: "15:30",
    slot_minutes: 30,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111104",
    slug: "nadia-haddad",
    name: "Nadia Haddad",
    credentials: "MD, FAAP",
    specialty: "Pediatrics",
    bio: "Nadia sees newborns through eighteen-year-olds, with a special interest in childhood asthma and developmental screening. Famous among local parents for same-week sick visits and never rushing a worried question.",
    photo_url: photo("photo-1594824476967-48c8b964273f"),
    years_experience: 9,
    rating: 5.0,
    reviews_count: 521,
    languages: ["English", "Arabic", "French"],
    education: "American University of Beirut · Residency at CHOP",
    consultation_fee: 130,
    location: "Children's Suite · Floor 1",
    working_days: [1, 2, 3, 4, 5],
    start_time: "08:30",
    end_time: "16:30",
    slot_minutes: 20,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111105",
    slug: "imani-clarke",
    name: "Imani Clarke",
    credentials: "MD, FAAD",
    specialty: "Dermatology",
    bio: "Medical and surgical dermatology, with deep experience in skin-of-color conditions and full-body cancer screening. Imani also runs the clinic's teledermatology triage, which is why her in-person slots move fast.",
    photo_url: photo("photo-1651008376811-b90baee60c1f"),
    years_experience: 12,
    rating: 4.8,
    reviews_count: 298,
    languages: ["English"],
    education: "Howard University COM · Residency at NYU Langone",
    consultation_fee: 210,
    location: "Dermatology Suite · Floor 3",
    working_days: [2, 3, 4],
    start_time: "09:00",
    end_time: "16:00",
    slot_minutes: 30,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111106",
    slug: "daniel-nguyen",
    name: "Daniel Nguyen",
    credentials: "MD, ECNU",
    specialty: "Endocrinology",
    bio: "Diabetes, thyroid disease, and metabolic health. Daniel co-designed Northlake's continuous-glucose-monitor program and spends most visits translating lab numbers into things you can act on this week.",
    photo_url: photo("photo-1622902046580-2b47f47f5471"),
    years_experience: 13,
    rating: 4.7,
    reviews_count: 194,
    languages: ["English", "Vietnamese"],
    education: "UCLA David Geffen SOM · Fellowship at Mayo Clinic",
    consultation_fee: 205,
    location: "Metabolic Health · Floor 3",
    working_days: [1, 3, 4, 5],
    start_time: "09:30",
    end_time: "17:30",
    slot_minutes: 45,
    is_active: true,
  },
];
