-- ============================================================================
-- AI Receptionist — provider roster seed
-- GENERATED by scripts/generate-seed-sql.ts from src/verticals/*/roster.ts.
-- Do not edit by hand; run `npm run seed:sql`.
-- Run after schema.sql. Safe to re-run: rows are upserted by (vertical, slug).
-- ============================================================================

insert into public.providers (
  id, vertical, slug, name, credentials, specialty, bio, photo_url, years_experience, rating, reviews_count, languages, education, consultation_fee, location, working_days, start_time, end_time, slot_minutes, is_active
) values
(
  '11111111-1111-4111-8111-111111111101', 'medical', 'elena-vasquez', 'Elena Vasquez', 'MD, FAAFP', 'Family Medicine',
  'Elena has spent seventeen years looking after families in the Northlake area — often three generations of the same one. She focuses on preventive care, chronic condition management, and the unglamorous work of catching things early.',
  'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  17, 4.9, 412, '{English,Spanish}', 'Johns Hopkins School of Medicine · Residency at UCSF',
  145, 'Northlake Main Clinic · Floor 2', '{1,2,3,4,5}', '09:00', '17:00', 30, true
),
(
  '11111111-1111-4111-8111-111111111102', 'medical', 'rahul-menon', 'Rahul Menon', 'MD, FACC', 'Cardiology',
  'Board-certified cardiologist with a subspecialty in preventive cardiology and heart failure. Rahul runs the clinic''s cardiac imaging program and believes most heart disease is a conversation that should have happened ten years earlier.',
  'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  14, 4.8, 287, '{English,Hindi,Malayalam}', 'AIIMS New Delhi · Fellowship at Cleveland Clinic',
  225, 'Cardiac Center · Floor 4', '{1,2,4,5}', '08:00', '16:00', 45, true
),
(
  '11111111-1111-4111-8111-111111111103', 'medical', 'marcus-bell', 'Marcus Bell', 'DO, CAQSM', 'Orthopedics & Sports Medicine',
  'Marcus treats everyone from weekend runners to the county''s high-school athletic programs. Non-surgical first, with ultrasound-guided injections and a rehab plan you will actually follow.',
  'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  11, 4.9, 356, '{English}', 'Michigan State COM · Sports Medicine Fellowship, Andrews Institute',
  190, 'Sports Medicine Wing · Floor 1', '{1,2,3,5,6}', '07:30', '15:30', 30, true
),
(
  '11111111-1111-4111-8111-111111111104', 'medical', 'nadia-haddad', 'Nadia Haddad', 'MD, FAAP', 'Pediatrics',
  'Nadia sees newborns through eighteen-year-olds, with a special interest in childhood asthma and developmental screening. Famous among local parents for same-week sick visits and never rushing a worried question.',
  'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  9, 5, 521, '{English,Arabic,French}', 'American University of Beirut · Residency at CHOP',
  130, 'Children''s Suite · Floor 1', '{1,2,3,4,5}', '08:30', '16:30', 20, true
),
(
  '11111111-1111-4111-8111-111111111105', 'medical', 'imani-clarke', 'Imani Clarke', 'MD, FAAD', 'Dermatology',
  'Medical and surgical dermatology, with deep experience in skin-of-color conditions and full-body cancer screening. Imani also runs the clinic''s teledermatology triage, which is why her in-person slots move fast.',
  'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  12, 4.8, 298, '{English}', 'Howard University COM · Residency at NYU Langone',
  210, 'Dermatology Suite · Floor 3', '{2,3,4}', '09:00', '16:00', 30, true
),
(
  '11111111-1111-4111-8111-111111111106', 'medical', 'daniel-nguyen', 'Daniel Nguyen', 'MD, ECNU', 'Endocrinology',
  'Diabetes, thyroid disease, and metabolic health. Daniel co-designed Northlake''s continuous-glucose-monitor program and spends most visits translating lab numbers into things you can act on this week.',
  'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  13, 4.7, 194, '{English,Vietnamese}', 'UCLA David Geffen SOM · Fellowship at Mayo Clinic',
  205, 'Metabolic Health · Floor 3', '{1,3,4,5}', '09:30', '17:30', 45, true
),
(
  '11111111-1111-4111-8111-111111110201', 'salon', 'sasha-reyes', 'Sasha Reyes', 'Master Colourist', 'Colour',
  'Sasha has spent twelve years doing the colour other salons send people to her to fix. Balayage, lived-in blondes, and corrective work — she''ll tell you honestly what your hair can take in one sitting and what it can''t.',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  12, 4.9, 388, '{English,Spanish}', 'Vidal Sassoon Academy · Wella Master Colour Expert',
  145, 'Colour bar · Ground floor', '{2,3,4,5,6}', '09:00', '18:00', 90, true
),
(
  '11111111-1111-4111-8111-111111110202', 'salon', 'theo-lindqvist', 'Theo Lindqvist', 'Senior Stylist', 'Cutting & styling',
  'Precision cuts and the kind of blowout that survives a commute. Theo trained in London and still cuts dry first, because that''s how you actually wear it.',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  9, 4.8, 302, '{English,Swedish}', 'Toni&Guy Academy, London',
  85, 'Main floor', '{1,2,3,4,5}', '10:00', '19:00', 60, true
),
(
  '11111111-1111-4111-8111-111111110203', 'salon', 'marcus-oyelaran', 'Marcus Oyelaran', 'Barber', 'Barbering',
  'Fades, scissor cuts, hot-towel shaves and beard shaping. Marcus keeps a chair free most days for walk-ins, but regulars book — his Saturdays go a week out.',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  7, 4.9, 411, '{English}', 'Apprenticed at Ruffians, Edinburgh',
  45, 'Barber chairs · Ground floor', '{1,2,3,5,6}', '09:00', '17:00', 30, true
),
(
  '11111111-1111-4111-8111-111111110204', 'salon', 'lina-farouk', 'Lina Farouk', 'Licensed Esthetician', 'Skin & facials',
  'Results-led facials, peels and LED, with a soft spot for skin that''s been overdone by too many products. Lina starts every first visit with a proper skin analysis before touching anything.',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  10, 5, 276, '{English,Arabic,French}', 'CIDESCO diploma · Dermalogica Expert',
  110, 'Treatment rooms · First floor', '{2,3,4,5,6}', '10:00', '18:00', 60, true
),
(
  '11111111-1111-4111-8111-111111110205', 'salon', 'priya-nair', 'Priya Nair', 'Massage Therapist', 'Massage',
  'Deep tissue, sports and prenatal massage. Priya trained in Thai massage in Chiang Mai and will absolutely find the knot you''ve been ignoring since March.',
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  11, 4.9, 349, '{English,Hindi}', 'CAMTC certified · Thai massage, Chiang Mai',
  120, 'Spa suite · First floor', '{1,3,4,5,6}', '10:00', '19:00', 60, true
),
(
  '11111111-1111-4111-8111-111111110206', 'salon', 'jonah-park', 'Jonah Park', 'Stylist', 'Cutting & styling',
  'Textured cuts, curls and the occasional brave fringe. Jonah is the one to book if you have a photo on your phone and aren''t sure it''ll work — he''ll tell you, kindly.',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  5, 4.7, 188, '{English,Korean}', 'Aveda Institute',
  70, 'Main floor', '{1,2,4,5,6}', '11:00', '20:00', 45, true
),
(
  '11111111-1111-4111-8111-111111110301', 'studio', 'mira-castellanos', 'Mira Castellanos', 'Creative Director', 'Brand identity',
  'Mira has led identity work for two IPOs and one very good bakery. She starts every project by asking what the company is afraid of looking like, and works backwards from there.',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  14, 4.9, 61, '{English,Spanish}', 'Pentagram · ArtCenter College of Design',
  250, 'Remote or in studio · SoMa', '{1,2,3,4}', '10:00', '16:00', 45, true
),
(
  '11111111-1111-4111-8111-111111110302', 'studio', 'owen-blackwood', 'Owen Blackwood', 'Strategy Director', 'Brand strategy',
  'Positioning, naming and the argument for why anyone should care. Owen''s sessions tend to end with a whiteboard photo and a shorter list of things to say.',
  'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  12, 4.8, 48, '{English}', 'Wolff Olins · London School of Economics',
  250, 'Remote', '{1,2,3,4,5}', '09:00', '17:00', 45, true
),
(
  '11111111-1111-4111-8111-111111110303', 'studio', 'anika-sato', 'Anika Sato', 'Design Director', 'Digital product',
  'Product design from first sketch to shipped release, with a preference for teams who will let her talk to actual users. Anika ran design at a fintech through its first million customers.',
  'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  10, 4.9, 57, '{English,Japanese}', 'Instrument · Rhode Island School of Design',
  250, 'Remote or in studio · SoMa', '{2,3,4,5}', '10:00', '18:00', 45, true
),
(
  '11111111-1111-4111-8111-111111110304', 'studio', 'tobias-reinholt', 'Tobias Reinholt', 'Motion Director', 'Motion & film',
  'Launch films, product motion and the thirty seconds that make a keynote land. Tobias will tell you in the first session whether your idea needs film or just a better still.',
  'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  9, 4.7, 39, '{English,German}', 'Buck · Filmakademie Baden-Württemberg',
  250, 'Remote', '{1,3,4,5}', '11:00', '19:00', 30, true
),
(
  '11111111-1111-4111-8111-111111110305', 'studio', 'celeste-nwosu', 'Celeste Nwosu', 'Head of Content', 'Content & copy',
  'Voice, messaging and the words on the button. Celeste came up through newsrooms and still edits like one — every sentence has to earn its place.',
  'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  11, 5, 44, '{English,French}', 'Wieden+Kennedy · Columbia Journalism School',
  250, 'Remote', '{1,2,4,5}', '09:30', '15:30', 30, true
),
(
  '11111111-1111-4111-8111-111111110306', 'studio', 'rafael-mendes', 'Rafael Mendes', 'Technical Director', 'Web & build',
  'The person who makes the design real and fast. Rafael scopes builds honestly, which occasionally means telling you the site you want is three sites.',
  'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  13, 4.8, 52, '{English,Portuguese}', 'Work & Co · University of São Paulo',
  250, 'Remote or in studio · SoMa', '{1,2,3,4,5}', '10:00', '17:00', 45, true
)
on conflict (vertical, slug) do update set
  name             = excluded.name,
  credentials      = excluded.credentials,
  specialty        = excluded.specialty,
  bio              = excluded.bio,
  photo_url        = excluded.photo_url,
  years_experience = excluded.years_experience,
  rating           = excluded.rating,
  reviews_count    = excluded.reviews_count,
  languages        = excluded.languages,
  education        = excluded.education,
  consultation_fee = excluded.consultation_fee,
  location         = excluded.location,
  working_days     = excluded.working_days,
  start_time       = excluded.start_time,
  end_time         = excluded.end_time,
  slot_minutes     = excluded.slot_minutes,
  is_active        = excluded.is_active;
