-- ============================================================================
-- AI Receptionist — provider roster seed
-- GENERATED by scripts/generate-seed-sql.ts from src/verticals/*/roster.ts.
-- Do not edit by hand; run `npm run seed:sql`.
-- Run after schema.sql. Safe to re-run: rows are upserted by slug.
-- ============================================================================

insert into public.providers (
  id, vertical, slug, name, credentials, specialty, bio, photo_url, years_experience, rating, reviews_count, languages, education, consultation_fee, location, working_days, start_time, end_time, slot_minutes, is_active
) values
(
  '11111111-1111-4111-8111-111111111101', 'medical', 'elena-vasquez', 'Elena Vasquez', 'MD, FAAFP', 'Family Medicine',
  'Elena has spent seventeen years looking after families in the Northlake area — often three generations of the same one. She focuses on preventive care, chronic condition management, and the unglamorous work of catching things early.',
  'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  17, 4.9, 412, '{English,Spanish}', 'Johns Hopkins School of Medicine · Residency at UCSF',
  145, 'Northlake Main Clinic · Floor 2', '{1,2,3,4,5}', '09:00', '17:00', 30, true
),
(
  '11111111-1111-4111-8111-111111111102', 'medical', 'rahul-menon', 'Rahul Menon', 'MD, FACC', 'Cardiology',
  'Board-certified cardiologist with a subspecialty in preventive cardiology and heart failure. Rahul runs the clinic''s cardiac imaging program and believes most heart disease is a conversation that should have happened ten years earlier.',
  'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  14, 4.8, 287, '{English,Hindi,Malayalam}', 'AIIMS New Delhi · Fellowship at Cleveland Clinic',
  225, 'Cardiac Center · Floor 4', '{1,2,4,5}', '08:00', '16:00', 45, true
),
(
  '11111111-1111-4111-8111-111111111103', 'medical', 'marcus-bell', 'Marcus Bell', 'DO, CAQSM', 'Orthopedics & Sports Medicine',
  'Marcus treats everyone from weekend runners to the county''s high-school athletic programs. Non-surgical first, with ultrasound-guided injections and a rehab plan you will actually follow.',
  'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  11, 4.9, 356, '{English}', 'Michigan State COM · Sports Medicine Fellowship, Andrews Institute',
  190, 'Sports Medicine Wing · Floor 1', '{1,2,3,5,6}', '07:30', '15:30', 30, true
),
(
  '11111111-1111-4111-8111-111111111104', 'medical', 'nadia-haddad', 'Nadia Haddad', 'MD, FAAP', 'Pediatrics',
  'Nadia sees newborns through eighteen-year-olds, with a special interest in childhood asthma and developmental screening. Famous among local parents for same-week sick visits and never rushing a worried question.',
  'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  9, 5, 521, '{English,Arabic,French}', 'American University of Beirut · Residency at CHOP',
  130, 'Children''s Suite · Floor 1', '{1,2,3,4,5}', '08:30', '16:30', 20, true
),
(
  '11111111-1111-4111-8111-111111111105', 'medical', 'imani-clarke', 'Imani Clarke', 'MD, FAAD', 'Dermatology',
  'Medical and surgical dermatology, with deep experience in skin-of-color conditions and full-body cancer screening. Imani also runs the clinic''s teledermatology triage, which is why her in-person slots move fast.',
  'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  12, 4.8, 298, '{English}', 'Howard University COM · Residency at NYU Langone',
  210, 'Dermatology Suite · Floor 3', '{2,3,4}', '09:00', '16:00', 30, true
),
(
  '11111111-1111-4111-8111-111111111106', 'medical', 'daniel-nguyen', 'Daniel Nguyen', 'MD, ECNU', 'Endocrinology',
  'Diabetes, thyroid disease, and metabolic health. Daniel co-designed Northlake''s continuous-glucose-monitor program and spends most visits translating lab numbers into things you can act on this week.',
  'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&crop=faces&w=640&h=640&q=80',
  13, 4.7, 194, '{English,Vietnamese}', 'UCLA David Geffen SOM · Fellowship at Mayo Clinic',
  205, 'Metabolic Health · Floor 3', '{1,3,4,5}', '09:30', '17:30', 45, true
)
on conflict (slug) do update set
  vertical         = excluded.vertical,
  name             = excluded.name,
  credentials      = excluded.credentials,
  specialty        = excluded.specialty,
  bio              = excluded.bio,
  photo_url        = excluded.photo_url,
  years_experience = excluded.years_experience,
  rating           = excluded.rating,
  reviews_count    = excluded.reviews_count,
  languages        = excluded.languages,
  education        = excluded.education,
  consultation_fee = excluded.consultation_fee,
  location         = excluded.location,
  working_days     = excluded.working_days,
  start_time       = excluded.start_time,
  end_time         = excluded.end_time,
  slot_minutes     = excluded.slot_minutes,
  is_active        = excluded.is_active;
