import type { Provider } from "@/lib/types";

const photo = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&crop=faces&w=640&h=640&q=80`;

/**
 * The studio's directors. Serves the demo directly and feeds `npm run seed:sql`,
 * so it must stay free of runtime imports (type-only is fine).
 */
const ROSTER: Omit<Provider, "vertical">[] = [
  {
    id: "11111111-1111-4111-8111-111111110301",
    slug: "mira-castellanos",
    name: "Mira Castellanos",
    credentials: "Creative Director",
    specialty: "Brand identity",
    bio: "Mira has led identity work for two IPOs and one very good bakery. She starts every project by asking what the company is afraid of looking like, and works backwards from there.",
    photo_url: photo("photo-1517841905240-472988babdf9"),
    years_experience: 14,
    rating: 4.9,
    reviews_count: 61,
    languages: ["English", "Spanish"],
    education: "Pentagram · ArtCenter College of Design",
    consultation_fee: 250,
    location: "Remote or in studio · SoMa",
    working_days: [1, 2, 3, 4],
    start_time: "10:00",
    end_time: "16:00",
    slot_minutes: 45,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110302",
    slug: "owen-blackwood",
    name: "Owen Blackwood",
    credentials: "Strategy Director",
    specialty: "Brand strategy",
    bio: "Positioning, naming and the argument for why anyone should care. Owen's sessions tend to end with a whiteboard photo and a shorter list of things to say.",
    photo_url: photo("photo-1539571696357-5a69c17a67c6"),
    years_experience: 12,
    rating: 4.8,
    reviews_count: 48,
    languages: ["English"],
    education: "Wolff Olins · London School of Economics",
    consultation_fee: 250,
    location: "Remote",
    working_days: [1, 2, 3, 4, 5],
    start_time: "09:00",
    end_time: "17:00",
    slot_minutes: 45,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110303",
    slug: "anika-sato",
    name: "Anika Sato",
    credentials: "Design Director",
    specialty: "Digital product",
    bio: "Product design from first sketch to shipped release, with a preference for teams who will let her talk to actual users. Anika ran design at a fintech through its first million customers.",
    photo_url: photo("photo-1524504388940-b1c1722653e1"),
    years_experience: 10,
    rating: 4.9,
    reviews_count: 57,
    languages: ["English", "Japanese"],
    education: "Instrument · Rhode Island School of Design",
    consultation_fee: 250,
    location: "Remote or in studio · SoMa",
    working_days: [2, 3, 4, 5],
    start_time: "10:00",
    end_time: "18:00",
    slot_minutes: 45,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110304",
    slug: "tobias-reinholt",
    name: "Tobias Reinholt",
    credentials: "Motion Director",
    specialty: "Motion & film",
    bio: "Launch films, product motion and the thirty seconds that make a keynote land. Tobias will tell you in the first session whether your idea needs film or just a better still.",
    photo_url: photo("photo-1519345182560-3f2917c472ef"),
    years_experience: 9,
    rating: 4.7,
    reviews_count: 39,
    languages: ["English", "German"],
    education: "Buck · Filmakademie Baden-Württemberg",
    consultation_fee: 250,
    location: "Remote",
    working_days: [1, 3, 4, 5],
    start_time: "11:00",
    end_time: "19:00",
    slot_minutes: 30,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110305",
    slug: "celeste-nwosu",
    name: "Celeste Nwosu",
    credentials: "Head of Content",
    specialty: "Content & copy",
    bio: "Voice, messaging and the words on the button. Celeste came up through newsrooms and still edits like one — every sentence has to earn its place.",
    photo_url: photo("photo-1488426862026-3ee34a7d66df"),
    years_experience: 11,
    rating: 5.0,
    reviews_count: 44,
    languages: ["English", "French"],
    education: "Wieden+Kennedy · Columbia Journalism School",
    consultation_fee: 250,
    location: "Remote",
    working_days: [1, 2, 4, 5],
    start_time: "09:30",
    end_time: "15:30",
    slot_minutes: 30,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110306",
    slug: "rafael-mendes",
    name: "Rafael Mendes",
    credentials: "Technical Director",
    specialty: "Web & build",
    bio: "The person who makes the design real and fast. Rafael scopes builds honestly, which occasionally means telling you the site you want is three sites.",
    photo_url: photo("photo-1573497019940-1c28c88b4f3e"),
    years_experience: 13,
    rating: 4.8,
    reviews_count: 52,
    languages: ["English", "Portuguese"],
    education: "Work & Co · University of São Paulo",
    consultation_fee: 250,
    location: "Remote or in studio · SoMa",
    working_days: [1, 2, 3, 4, 5],
    start_time: "10:00",
    end_time: "17:00",
    slot_minutes: 45,
    is_active: true,
  },
];

export const STUDIO_ROSTER: Provider[] = ROSTER.map((p) => ({ ...p, vertical: "studio" }));
