import type { Appointment, CallLog, Client } from "@/lib/types";
import { DAY, iso, slotFor } from "../seed-utils";
import { STUDIO_ROSTER as R } from "./roster";

/** Tier C: the clients, sessions and transcripts that make the studio's dashboard look lived-in. */
export function buildStudioSeed(now: number) {
  const clients: Client[] = [
    {
      id: "22222222-2222-4222-8222-222222220301",
      full_name: "Nadia Feld",
      phone: "+1 415 555 0134",
      email: "nadia@lumenrobotics.example.com",
      notes: null,
      created_at: iso(now - 5 * DAY),
    },
    {
      id: "22222222-2222-4222-8222-222222220302",
      full_name: "Elliot Vance",
      phone: "+1 415 555 0152",
      email: "elliot@northwind.example.com",
      notes: null,
      created_at: iso(now - 3 * DAY),
    },
    {
      id: "22222222-2222-4222-8222-222222220303",
      full_name: "Sofia Marin",
      phone: "+1 415 555 0116",
      email: "sofia@marinandco.example.com",
      notes: null,
      created_at: iso(now - 2 * DAY),
    },
    {
      id: "22222222-2222-4222-8222-222222220304",
      full_name: "Kenji Watanabe",
      phone: "+1 415 555 0179",
      email: null,
      notes: null,
      created_at: iso(now - 1 * DAY),
    },
  ];

  const appointments: Appointment[] = [
    {
      id: "33333333-3333-4333-8333-333333330301",
      vertical: "studio",
      reference: "HS-3MK7TB",
      provider_id: R[0].id,
      client_id: clients[0].id,
      ...slotFor(R[0], 2, 11, 0),
      reason: "Rebrand ahead of a Series A — name, identity and site.",
      status: "confirmed",
      is_new_client: true,
      created_at: iso(now - 5 * DAY),
      updated_at: iso(now - 5 * DAY + 85_000),
    },
    {
      id: "33333333-3333-4333-8333-333333330302",
      vertical: "studio",
      reference: "HS-7QW2NA",
      provider_id: R[1].id,
      client_id: clients[1].id,
      ...slotFor(R[1], 3, 14, 0),
      reason: "Positioning for a second product line.",
      status: "confirmed",
      is_new_client: false,
      created_at: iso(now - 3 * DAY),
      updated_at: iso(now - 3 * DAY + 100_000),
    },
    {
      id: "33333333-3333-4333-8333-333333330303",
      vertical: "studio",
      reference: "HS-5RD8XL",
      provider_id: R[2].id,
      client_id: clients[2].id,
      ...slotFor(R[2], 1, 15, 0),
      reason: "Onboarding flow redesign — drop-off at step two.",
      status: "rescheduled",
      is_new_client: true,
      created_at: iso(now - 2 * DAY),
      updated_at: iso(now - 2 * DAY + 190_000),
    },
    {
      id: "33333333-3333-4333-8333-333333330304",
      vertical: "studio",
      reference: "HS-9PB4EC",
      provider_id: R[3].id,
      client_id: clients[3].id,
      ...slotFor(R[3], 4, 13, 0),
      reason: "Launch film for a hardware product.",
      // Matches its call log: the assistant rang and nobody picked up.
      status: "no_answer",
      is_new_client: true,
      created_at: iso(now - 1 * DAY),
      updated_at: iso(now - 1 * DAY),
    },
  ];

  const calls: CallLog[] = [
    {
      id: "44444444-4444-4444-8444-444444440301",
      appointment_id: appointments[0].id,
      client_id: clients[0].id,
      provider: "demo",
      kind: "confirmation",
      demo_phone: null,
      demo_business: null,
      demo_name: null,
      reference: null,
      provider_call_id: "demo_call_3MK7TB",
      direction: "outbound",
      status: "completed",
      outcome: "confirmed",
      recording_url: "/audio/sample-call.wav",
      transcript: [
        "Agent: Hi, this is Jules calling from Halide Studio. Am I speaking with Nadia Feld?",
        "Nadia: Yes, that's me.",
        "Agent: Great. I'm confirming your discovery session with Mira about the rebrand. Does that time still work for you?",
        "Nadia: It does.",
        "Agent: Perfect, you're confirmed. If there's a deck or a site you'd like Mira to look at beforehand, just reply to the confirmation email with a link. Anything else I can help with?",
        "Nadia: No, that's all. Thanks.",
        "Agent: Speak soon, Nadia.",
      ].join("\n"),
      summary:
        "Client confirmed the session. New client — brief form to be emailed. Asked to send any existing materials ahead of time.",
      duration_seconds: 44,
      cost: 0.11,
      error: null,
      started_at: iso(now - 5 * DAY + 30_000),
      ended_at: iso(now - 5 * DAY + 74_000),
      created_at: iso(now - 5 * DAY + 5_000),
    },
    {
      id: "44444444-4444-4444-8444-444444440302",
      appointment_id: appointments[1].id,
      client_id: clients[1].id,
      provider: "demo",
      kind: "confirmation",
      demo_phone: null,
      demo_business: null,
      demo_name: null,
      reference: null,
      provider_call_id: "demo_call_7QW2NA",
      direction: "outbound",
      status: "completed",
      outcome: "confirmed",
      recording_url: "/audio/sample-call.wav",
      transcript: [
        "Agent: Good afternoon, this is Jules from Halide Studio calling for Elliot Vance.",
        "Elliot: Speaking.",
        "Agent: I'm confirming your session with Owen on positioning for the second product line. Shall I keep it as scheduled?",
        "Elliot: Yes, keep it. Can you tell me roughly what a strategy engagement costs?",
        "Agent: I can't quote that, but Owen will scope it with you in the session and follow up in writing.",
        "Elliot: Fair enough.",
        "Agent: You're all set. Thanks, Elliot.",
      ].join("\n"),
      summary:
        "Confirmed. Returning client. Asked about engagement cost — deferred to the director per policy.",
      duration_seconds: 58,
      cost: 0.14,
      error: null,
      started_at: iso(now - 3 * DAY + 38_000),
      ended_at: iso(now - 3 * DAY + 96_000),
      created_at: iso(now - 3 * DAY + 6_000),
    },
    {
      id: "44444444-4444-4444-8444-444444440303",
      appointment_id: appointments[2].id,
      client_id: clients[2].id,
      provider: "demo",
      kind: "confirmation",
      demo_phone: null,
      demo_business: null,
      demo_name: null,
      reference: null,
      provider_call_id: "demo_call_5RD8XL",
      direction: "outbound",
      status: "completed",
      outcome: "rescheduled",
      recording_url: "/audio/sample-call.wav",
      transcript: [
        "Agent: Hello, this is Jules at Halide Studio, calling for Sofia Marin.",
        "Sofia: Hi — yes, but that afternoon just got taken by a board meeting.",
        "Agent: No problem at all. Anika has space the following morning or later that week. Would either suit?",
        "Sofia: The following morning, ideally early.",
        "Agent: I've noted that, and the studio will email you a new time to confirm within the hour.",
        "Sofia: Perfect, thanks.",
      ].join("\n"),
      summary:
        "Client cannot attend the booked slot. Requested the following morning, early. Flagged for rebooking.",
      duration_seconds: 47,
      cost: 0.12,
      error: null,
      started_at: iso(now - 2 * DAY + 34_000),
      ended_at: iso(now - 2 * DAY + 81_000),
      created_at: iso(now - 2 * DAY + 4_000),
    },
    {
      id: "44444444-4444-4444-8444-444444440304",
      appointment_id: appointments[3].id,
      client_id: clients[3].id,
      provider: "demo",
      kind: "confirmation",
      demo_phone: null,
      demo_business: null,
      demo_name: null,
      reference: null,
      provider_call_id: "demo_call_9PB4EC",
      direction: "outbound",
      status: "completed",
      outcome: "no_answer",
      recording_url: null,
      transcript: null,
      summary: "No answer after four rings. Voicemail was not available. Retry queued.",
      duration_seconds: 20,
      cost: 0.03,
      error: null,
      started_at: iso(now - 1 * DAY + 30_000),
      ended_at: iso(now - 1 * DAY + 50_000),
      created_at: iso(now - 1 * DAY + 3_000),
    },
  ];

  return { clients, appointments, calls };
}
