"use client";
import {useEffect,useState} from 'react';
import {businessPreferences,applyBusinessPreferences,type BusinessPreferences} from '@/lib/platform/business-preferences';
import type {BusinessConfig} from '@/lib/platform/model';
import {validateSetupDraft} from '@/lib/platform/setup-draft';
import {ANSWERING_PREFERENCES} from '@/lib/platform/answering-preference';
import {WeeklyHoursEditor} from './weekly-hours-editor';
import {PhoneProviderFields} from './phone-provider-fields';
import {PREVIEW_DRAFT_KEY} from './use-setup-autosave';
import styles from './business-preferences-form.module.css';
const fallback:BusinessConfig={trade:'salon',address:'123 Example Street, Detroit, MI',phone:'3135550142',areaCode:'313',color:'#315e4c',timezone:'America/Detroit',days:[1,2,3,4,5],opens:'09:00',closes:'17:00',team:[{id:'member-1',name:'Willow Studio',service:'Appointment',minutes:45}]};
const zones:Record<string,string>={'America/New_York':'Eastern Time','America/Detroit':'Eastern Time (Michigan)','America/Chicago':'Central Time','America/Denver':'Mountain Time','America/Los_Angeles':'Pacific Time','America/Phoenix':'Arizona Time','America/Anchorage':'Alaska Time','Pacific/Honolulu':'Hawaii Time'};
export function BusinessPreferencesForm({initial,initialRevision='',preview=false}:{initial?:BusinessPreferences;initialRevision?:string;preview?:boolean}){
 const [value,setValue]=useState(initial??businessPreferences({business_name:'Willow Studio',config:fallback}));
 const [revision,setRevision]=useState(initialRevision),[ready,setReady]=useState(!preview),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{if(!preview)return;try{const raw=localStorage.getItem(PREVIEW_DRAFT_KEY);if(raw){const d=validateSetupDraft(JSON.parse(raw));setValue(businessPreferences({business_name:d.details.business_name||'Willow Studio',config:{...fallback,...d.details,trade:(d.details.trade||'salon') as BusinessConfig['trade'],timezone:d.timezone,days:d.days,opens:d.opens,closes:d.closes,weeklyHours:d.weeklyHours,team:d.team.length?d.team:fallback.team,phoneSetup:{provider:d.details.phoneProvider as NonNullable<BusinessConfig['phoneSetup']>['provider']||'unknown',serviceType:d.details.phoneServiceType as NonNullable<BusinessConfig['phoneSetup']>['serviceType']||'unknown',serviceName:d.details.phoneServiceName,bookingSystem:d.details.bookingSystem},answeringPreference:(d.details.answeringPreference||"undecided") as BusinessConfig['answeringPreference']}}));}}catch{}setReady(true);},[preview]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 useEffect(()=>{if(!ready)return;const frame=requestAnimationFrame(()=>{if(["#business-details","#hours-availability","#phone-preferences"].includes(location.hash))document.getElementById(location.hash.slice(1))?.scrollIntoView({block:"start"});});return()=>cancelAnimationFrame(frame);},[ready]);
 function change(patch:Partial<BusinessPreferences>){setValue(v=>({...v,...patch}));setDirty(true);setMessage('');}
 if(!ready)return <p role="status">Loading your business…</p>;
 return <form className={styles.form} onChange={()=>{setDirty(true);setMessage('');}} onSubmit={async event=>{event.preventDefault();if(busy)return;const data=new FormData(event.currentTarget);const preferences={...value,phoneSetup:{provider:data.get('phoneProvider'),serviceType:data.get('phoneServiceType'),serviceName:data.get('phoneServiceName'),bookingSystem:data.get('bookingSystem')}};setBusy(true);setFailed(false);setMessage('');try{
  if(preview){const updated=applyBusinessPreferences({business_name:value.business_name,config:{...fallback,team:[{...fallback.team[0],name:value.business_name}]}},preferences);const p=businessPreferences(updated);const open=p.weeklyHours.filter(d=>d.enabled);localStorage.setItem(PREVIEW_DRAFT_KEY,JSON.stringify({details:{business_name:p.business_name,trade:p.trade,address:p.address,phone:p.phone,areaCode:p.areaCode,color:fallback.color,phoneProvider:p.phoneSetup.provider,phoneServiceType:p.phoneSetup.serviceType,phoneServiceName:p.phoneSetup.serviceName,bookingSystem:p.phoneSetup.bookingSystem,answeringPreference:p.answeringPreference},weeklyHours:p.weeklyHours,days:open.map(d=>d.day),opens:open[0].opens,closes:open[0].closes,timezone:p.timezone,team:updated.config.team}));setValue(p);setMessage('Saved on this device. Your setup preview uses these details too.');}
  else{const response=await fetch('/api/account/business-preferences',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({preferences,revision})});const result=await response.json();if(!response.ok)throw Error(result.error);setRevision(result.revision);setValue(result.preferences);setMessage('Business settings saved. Existing appointments are unchanged.');}setDirty(false);
 }catch(error){setFailed(true);setMessage(error instanceof Error?error.message:'Could not save your changes.');}finally{setBusy(false);}}}>
 <fieldset disabled={busy} id="business-details" tabIndex={-1}><legend>Business details</legend><p>Keep your business information up to date.</p><div className={styles.fields}>
 <label>Business name<input required maxLength={120} value={value.business_name} onChange={e=>change({business_name:e.target.value})}/></label>
 <label>Business type<select value={value.trade} onChange={e=>change({trade:e.target.value as BusinessPreferences['trade']})}><option value="salon">Salon, spa or wellness</option><option value="studio">Creative studio</option><option value="other">Other appointment business</option></select></label>
 <label>Business address<input required autoComplete="street-address" maxLength={300} value={value.address} onChange={e=>change({address:e.target.value})}/></label>
 <label>Business contact phone<input type="tel" required value={value.phone} onChange={e=>change({phone:e.target.value})}/></label>
 </div></fieldset>
 <fieldset disabled={busy} id="hours-availability" tabIndex={-1}><legend>Hours & availability</legend><p>These hours control new bookings for this location. Existing appointments stay in place.</p><label>Location time zone<select value={value.timezone} onChange={e=>change({timezone:e.target.value})}>{Array.from(new Set([...Object.keys(zones),value.timezone])).map(z=><option key={z} value={z}>{zones[z]??z}</option>)}</select></label>
 <WeeklyHoursEditor value={value.weeklyHours} onChange={weeklyHours=>change({weeklyHours})}/><label>Appointment length<select value={value.appointmentMinutes} onChange={e=>change({appointmentMinutes:Number(e.target.value)})}>{Array.from({length:16},(_,i)=>(i+1)*15).map(m=><option key={m} value={m}>{m} minutes</option>)}</select></label>
 </fieldset>
 <div id="phone-preferences"><PhoneProviderFields initial={value.phoneSetup} disabled={busy} editing/><fieldset disabled={busy}><legend>Call preferences</legend><p>These details help us plan your phone setup. They don’t replace a connected number or change live call routing.</p><div className={styles.fields}><label>Preferred area code for a new number<input required pattern="[0-9]{3}" value={value.areaCode} onChange={e=>change({areaCode:e.target.value})}/></label><label>AI answering preference<select value={value.answeringPreference} onChange={e=>change({answeringPreference:e.target.value as BusinessPreferences['answeringPreference']})}>{Object.entries(ANSWERING_PREFERENCES).map(([key,item])=><option key={key} value={key}>{item.label}</option>)}</select></label></div><p>Manage your connected phone from your <a href={preview?'/account?preview=confirmation':'/account'}>account dashboard</a>.</p></fieldset></div>
 <div className={styles.save}><button type="submit" disabled={busy||!dirty}>{busy?'Saving…':'Save business settings'}</button><p role={failed?'alert':'status'}>{message||(dirty?'You have unsaved changes.':'Your saved business settings.')}</p></div>
 </form>;
}
