"use client";
import { useState } from "react";
import { DEFAULT_PHONE_SETUP, PHONE_PROVIDERS, phoneSetupGuidance, type PhoneSetup } from "@/lib/platform/phone-provider";
const simpleBooking=["Not sure yet","No appointment system yet","Paper calendar"];
export function PhoneProviderFields({ initial, disabled=false, editing=false }: { initial?: PhoneSetup; disabled?:boolean; editing?:boolean }) {
 const [setup,setSetup]=useState(initial??DEFAULT_PHONE_SETUP);
 const [booking,setBooking]=useState(!initial?.bookingSystem?"Not sure yet":simpleBooking.includes(initial.bookingSystem)?initial.bookingSystem:"software");
 const known=setup.provider!=="unknown"&&setup.provider!=="none";
 return <fieldset disabled={disabled}><legend>Your phone and appointment book</legend><p>{editing?"Keep your provider and appointment system details current. Choose ‘Not sure yet’ for anything you don’t know.":"Share what you know. You can leave the rest as ‘Not sure yet’ and we’ll work through it with you."}</p><div className="platform-fields">
 <label className="platform-fieldbox"><span>Who provides your phone service?</span><select name="phoneProvider" value={setup.provider} onChange={e=>setSetup({...setup,provider:e.target.value as PhoneSetup['provider']})}>{Object.entries(PHONE_PROVIDERS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 {known?<><label className="platform-fieldbox"><span>Type of phone service (if known)</span><select name="phoneServiceType" value={setup.serviceType} onChange={e=>setSetup({...setup,serviceType:e.target.value as PhoneSetup['serviceType']})}><option value="unknown">Not sure yet</option><option value="business_line">Business phone line</option><option value="cloud_phone">Cloud phone system / office extensions</option><option value="mobile">Mobile phone</option></select></label><label className="platform-fieldbox"><span>Service or plan name (optional)</span><input name="phoneServiceName" maxLength={160} defaultValue={initial?.serviceName??""} placeholder="You can leave this blank"/></label></>:<><input type="hidden" name="phoneServiceType" value="unknown"/><input type="hidden" name="phoneServiceName" value=""/></>}
 <label className="platform-fieldbox"><span>How do you keep track of appointments?</span><select name={booking==='software'?undefined:'bookingSystem'} value={booking} onChange={e=>setBooking(e.target.value)}><option value="Not sure yet">I’m not sure yet</option><option value="No appointment system yet">I don’t have a system yet</option><option value="Paper calendar">Paper calendar or appointment book</option><option value="software">An app or booking software</option></select></label>
 {booking==='software'&&<label className="platform-fieldbox"><span>App or software name (optional)</span><input name="bookingSystem" maxLength={160} defaultValue={initial?.bookingSystem&&!simpleBooking.includes(initial.bookingSystem)?initial.bookingSystem:""} placeholder="For example, Square or Fresha"/><small>Don’t know the name? Leave this blank.</small></label>}
 </div><p className="platform-note" role="status">{phoneSetupGuidance(setup)}</p><p className="platform-note">{editing?"Changing these details does not connect or disconnect a phone or booking system. Contact support if your service has changed.":booking==='No appointment system yet'?"We’ll prepare your booking page and help you get started. You don’t need to buy booking software to finish this form.":booking==='software'?"We’ll review compatibility before connecting any existing booking software.":"Your new booking page is part of setup. We’ll help you decide how to manage appointments."}</p></fieldset>;
}
