"use client";
import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {minuteTime,timeMinutes} from '@/lib/platform/weekly-hours';
import styles from './time-field.module.css';
const format=(n:number)=>`${Math.floor(n/60)%12||12}:${String(n%60).padStart(2,'0')} ${n<720||n===1440?'AM':'PM'}`;
export function TimeField({label,value,min,max,disabled,onChange}:{label:string;value:string;min:number;max:number;disabled:boolean;onChange:(minutes:number)=>void}){
 const anchor=useRef({top:0,left:0});const id=useId(),input=useRef<HTMLInputElement>(null),panel=useRef<HTMLDivElement>(null);const [text,setText]=useState(format(timeMinutes(value))),[open,setOpen]=useState(false),[active,setActive]=useState<number|null>(null),[error,setError]=useState('');const [position,setPosition]=useState({top:0,left:0,fontFamily:'inherit'});
 const options=Array.from({length:97},(_,i)=>i*15).filter(n=>n>=min&&n<=max);
 useEffect(()=>{setText(format(timeMinutes(value)));setError('');input.current?.setCustomValidity('');},[value]);
 function pick(n:number){setText(format(n));setError('');input.current?.setCustomValidity('');onChange(n);setOpen(false);setActive(null);}
 function commit(){const m=text.trim().match(/^(\d{1,2})(?::?(\d{2}))?\s*(am|pm|a|p)?$/i);let n=-1;if(m){let h=Number(m[1]),minutes=Number(m[2]??0);const period=m[3]?.toLowerCase();if(minutes<60&&h<=24){if(period&&h>=1&&h<=12)h=h%12+(period.startsWith('p')?12:0);else if(period)h=99;else if(h<=12)h=h%12+(timeMinutes(value)>=720&&timeMinutes(value)<1440?12:0);n=h*60+minutes;if(n===0&&max===1440)n=1440;}}if(n<min||n>max||n%15!==0){const message=`Use a time from ${format(min)} to ${format(max)} in 15-minute steps.`;setError(message);input.current?.setCustomValidity(message);return;}pick(n);}
 function show(){if(disabled)return;const r=input.current!.getBoundingClientRect();anchor.current={top:r.top,left:r.left};setPosition({left:Math.max(8,Math.min(r.left,innerWidth-192)),top:r.bottom+260>innerHeight?Math.max(8,r.top-260):r.bottom+6,fontFamily:getComputedStyle(input.current!).fontFamily});setActive(timeMinutes(value));setOpen(true);}
 useEffect(()=>{if(!open)return;const close=(e:Event)=>{if(panel.current?.contains(e.target as Node)||input.current?.parentElement?.contains(e.target as Node))return;if(e.type==='scroll'){const r=input.current?.getBoundingClientRect();if(r&&Math.abs(r.top-anchor.current.top)<1&&Math.abs(r.left-anchor.current.left)<1)return;}setOpen(false);};window.addEventListener('pointerdown',close);window.addEventListener('scroll',close,true);window.addEventListener('resize',close);requestAnimationFrame(()=>panel.current?.querySelector('[aria-selected="true"]')?.scrollIntoView({block:'nearest'}));return()=>{window.removeEventListener('pointerdown',close);window.removeEventListener('scroll',close,true);window.removeEventListener('resize',close);};},[open]);
 return <div className={styles.root}><div className={styles.control}><input ref={input} type="text" aria-label={label} role="combobox" aria-expanded={open} aria-controls={open?`${id}-list`:undefined} aria-autocomplete="none" aria-activedescendant={open&&active!==null?`${id}-${active}`:undefined} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined} disabled={disabled} value={text} autoComplete="off" spellCheck={false} onFocus={e=>e.currentTarget.select()} onChange={e=>{setText(e.target.value);setActive(null);setError('');e.currentTarget.setCustomValidity('');}} onBlur={()=>{commit();setOpen(false);}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setText(format(timeMinutes(value)));setError('');input.current?.setCustomValidity('');setOpen(false);}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!open){show();return;}const i=options.indexOf(active??timeMinutes(value));const n=options[Math.max(0,Math.min(options.length-1,i+(e.key==='ArrowDown'?1:-1)))];setActive(n);requestAnimationFrame(()=>document.getElementById(`${id}-${n}`)?.scrollIntoView({block:'nearest'}));}else if(e.key==='Enter'){e.preventDefault();if(open&&active!==null)pick(active);else commit();}}}/><button type="button" disabled={disabled} aria-label={`Choose ${label.toLowerCase()}`} aria-expanded={open} onMouseDown={e=>e.preventDefault()} onClick={()=>{if(open)setOpen(false);else{input.current?.focus();show();}}}><svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="m4 6 4 4 4-4" strokeLinecap="round" strokeLinejoin="round"/></svg></button></div>{error&&<small id={`${id}-error`} className={styles.error}>{error}</small>}{open&&createPortal(<div ref={panel} className={styles.panel} style={position}><div className={styles.caption}>Choose a time</div><div id={`${id}-list`} role="listbox" aria-label={label} className={styles.list}>{options.map(n=><div id={`${id}-${n}`} key={n} role="option" aria-selected={active===n} className={styles.option} onPointerDown={e=>e.preventDefault()} onClick={()=>pick(n)}>{format(n)}{n===1440&&<small>End of day</small>}{n===timeMinutes(value)&&<span aria-hidden="true">✓</span>}</div>)}</div></div>,document.body)}</div>;
}
