"use client";
import {useRef} from 'react';
import {DAY_NAMES,minuteTime,timeMinutes,type DayHours} from '@/lib/platform/weekly-hours';
import styles from './weekly-hours-editor.module.css';
const display=(time:string)=>time==='24:00'?'Midnight':`${Number(time.slice(0,2))%12||12}:${time.slice(3)} ${Number(time.slice(0,2))<12?'AM':'PM'}`;
function DayColumn({value,onChange}:{value:DayHours;onChange:(next:DayHours)=>void}){
 const track=useRef<HTMLDivElement>(null);const latest=useRef(value);latest.current=value;const name=DAY_NAMES[value.day];const start=timeMinutes(value.opens),end=timeMinutes(value.closes);const allDay=start===0&&end===1440;
 function changeTime(edge:'opens'|'closes',minutes:number){const current=latest.current;const m=edge==='opens'?Math.max(0,Math.min(minutes,timeMinutes(current.closes)-15)):Math.min(1440,Math.max(minutes,timeMinutes(current.opens)+15));const next={...current,[edge]:minuteTime(m)};latest.current=next;onChange(next);}
 function drag(edge:'opens'|'closes',y:number){const rect=track.current!.getBoundingClientRect();changeTime(edge,Math.round((y-rect.top)/rect.height*96)*15);}
 return <div className={styles.day} data-enabled={value.enabled}><label className={styles.dayToggle}><input type="checkbox" aria-label={`${name} open`} checked={value.enabled} onChange={e=>onChange({...value,enabled:e.target.checked})}/>{name.slice(0,3)}</label><button type="button" className={styles.allDay} disabled={!value.enabled} aria-label={`${name} all day`} aria-pressed={allDay&&value.enabled} onClick={()=>onChange({...value,opens:allDay?'09:00':'00:00',closes:allDay?'17:00':'24:00'})}>All day</button>
 <div ref={track} className={styles.track} aria-label={`${name} schedule`}>
 {value.enabled?<><div className={styles.fill} style={{top:`${start/14.4}%`,height:`${(end-start)/14.4}%`}}/>{(['opens','closes'] as const).map(edge=><button key={edge} type="button" role="slider" aria-label={`${name} ${edge==='opens'?'opening':'closing'} time`} aria-orientation="vertical" aria-valuemin={edge==='opens'?0:start+15} aria-valuemax={edge==='opens'?end-15:1440} aria-valuenow={edge==='opens'?start:end} aria-valuetext={display(value[edge])} className={styles.handle} data-edge={edge} style={{top:`${timeMinutes(value[edge])/14.4}%`}} onPointerDown={e=>{e.preventDefault();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))drag(edge,e.clientY);}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onKeyDown={e=>{let m=timeMinutes(value[edge]);if(['ArrowUp','ArrowLeft'].includes(e.key))m-=15;else if(['ArrowDown','ArrowRight'].includes(e.key))m+=15;else if(e.key==='Home')m=edge==='opens'?0:start+15;else if(e.key==='End')m=edge==='opens'?end-15:1440;else return;e.preventDefault();changeTime(edge,m);}}><span aria-hidden="true">═</span></button>)}<span className={styles.rangeLabel} style={{top:`${(start+end)/28.8}%`}}>{allDay?'24 hours':`${display(value.opens)} – ${display(value.closes)}`}</span></>:<span className={styles.closed}>Closed</span>}
 </div>
 <label className={styles.manual}>Opens<input type="time" aria-label={`${name} opens`} disabled={!value.enabled} value={value.opens} step={900} onChange={e=>{if(e.target.value)changeTime('opens',Math.round(timeMinutes(e.target.value)/15)*15);}}/></label>
 <label className={styles.manual}>Closes<input type="time" aria-label={`${name} closes`} disabled={!value.enabled} value={value.closes==='24:00'?'00:00':value.closes} step={900} onChange={e=>{if(e.target.value)changeTime('closes',e.target.value==='00:00'?1440:Math.round(timeMinutes(e.target.value)/15)*15);}}/></label>{value.closes==='24:00'&&value.enabled&&<small className={styles.midnight}>Midnight, end of day</small>}
 </div>;
}
export function WeeklyHoursEditor({value,onChange}:{value:DayHours[];onChange:(value:DayHours[])=>void}){return <div className={styles.scroller}><div className={styles.week}><div className={styles.axis} aria-hidden="true"><div>12 AM</div><div>6 AM</div><div>12 PM</div><div>6 PM</div><div>12 AM</div></div>{[1,2,3,4,5,6,0].map(day=><DayColumn key={day} value={value.find(d=>d.day===day)!} onChange={next=>onChange(value.map(d=>d.day===day?next:d))}/>)}</div></div>;}
