import { createRequire } from "node:module";
const require = createRequire(process.cwd() + "/package.json");
const { chromium } = require("playwright-core");
const [,, htmlPath, outPath] = process.argv;
const mode = process.argv[4] || "card";
const W = mode === "stage" ? 1600 : mode === "wide" ? 1200 : 820;
const H = mode === "stage" ? 1000 : mode === "wide" ? 760 : 964;
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: W, height: H }, deviceScaleFactor: 2 });
await page.goto("file://" + htmlPath, { waitUntil: "networkidle" });
await page.evaluate(() => document.fonts.ready);
await page.waitForTimeout(350);
await page.screenshot({ path: outPath, clip: { x: 0, y: 0, width: W, height: H } });
await browser.close();
console.log("rendered", outPath, W + "x" + H);
