import { createRequire } from "node:module";
const require = createRequire(process.cwd() + "/package.json");
const { chromium } = require("playwright-core");
const [,, htmlPath, outPath] = process.argv;
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 600, height: 640 }, deviceScaleFactor: 2 });
await page.goto("file://" + htmlPath, { waitUntil: "networkidle" });
await page.evaluate(() => document.fonts.ready);
await page.waitForTimeout(300);
await page.screenshot({ path: outPath, clip: { x: 0, y: 0, width: 600, height: 640 } });
await browser.close();
console.log("rendered", outPath);
