const brand = '<div class="brand">AI Receptionist</div>';
const field = (label, value) => `<div><div class="field-label">${label}</div><div class="field">${value}</div></div>`;
const button = text => `<div class="cta">${text}</div>`;
const screen = content => `<div class="window"><div class="window-bar"><i></i><i></i><i></i><span>SCREEN SKETCH · NOT AN ACTIVE FORM</span></div><div class="mock">${content}</div></div>`;

const owner = [
  { key:'discover', label:'Discover', sub:'Website + pricing', title:'“Could this help my business?”', status:'App flow', path:'Marketing site → pricing', lead:'An owner explores the product, sees a demo, then chooses “Start here” on a pricing plan.', actions:['See how online bookings and confirmation calls work.','Compare monthly minutes, setup costs and features.','Choose a plan to begin signup.'], next:'“Start here” opens the owner sign-in step if they are not signed in.', link:['Open original marketing preview','http://localhost:3102/'], mock:brand+'<div class="dark-hero"><small>MORE ROOM FOR YOUR WORK</small><h4>A front desk that gives you time back.</h4><small>Online bookings. AI confirmation calls. A clear view of what happened.</small></div><div class="grid"><div class="selection">Front desk<br><span class="price">$199</span> / month</div><div class="selection">Busy desk<br><span class="price">$399</span> / month</div></div>'+button('Start here →'), noteTitle:'The entry point', note:'This path begins on the original marketing site’s pricing cards. The luxury V2 page is still a design study; its buttons do not yet start signup.' },
  { key:'signin', label:'Sign in', sub:'Email → secure link', title:'Make it their own.', status:'App flow', path:'/account/login → inbox', lead:'The owner enters their email and opens a secure sign-in link. This connects the business setup to their account.', actions:['Enter an email address and complete the human check.','Open the sign-in email.','A new account continues to the business setup form.'], next:'The email link opens the account area. New owners automatically reach /start.', link:['Open sign-in preview','http://localhost:3102/account/login'], mock:brand+'<h4>Your front desk,<br>one sign-in away.</h4><small>Sign in to set up your business and check your bookings.</small><div style="margin-top:24px">'+field('Your email address','owner@example.com')+'</div>'+button('Email me a sign-in link →')+'<div class="line" style="margin-top:25px">✉ &nbsp; Open your inbox → follow the secure link</div>', noteTitle:'A gap to improve', note:'The pricing choice currently does not survive email sign-in. The owner chooses their plan again on the setup form. Email delivery also needs launch verification.' },
  { key:'setup', label:'Set up', sub:'Business + provider', title:'This is the screen you’re looking at.', status:'Built locally', path:'/start', lead:'After signing in, and before paying, the business owner tells us how their business and phone service work.', actions:['Choose a plan and review the payment breakdown.','Enter the business, phone provider and appointment software.','Set opening hours, team members and appointment lengths.'], next:'“Save and continue to secure checkout” saves the details, then opens Stripe.', link:['Open this setup screen','http://localhost:3102/start'], mock:brand+'<h4>A front desk of your own.</h4><div class="line">01 &nbsp; Your front desk <span style="float:right">Plan + payment breakdown</span></div><div class="line">02 &nbsp; Meet your business</div><div class="focus"><div class="focus-title">03 &nbsp; Your phone and appointment book</div><div class="grid">'+field('Phone provider','Comcast Business &nbsp;⌄')+field('Type of phone service','Business phone line &nbsp;⌄')+field('Service or plan name','If known')+field('Where do you manage appointments?','Software or calendar name')+'</div><small style="margin-top:10px">Provider selection helps prepare setup. It does not connect the line.</small></div><div class="line">04 &nbsp; When you’re open</div><div class="line">05 &nbsp; Who clients can book</div>'+button('Save and continue to secure checkout →'), noteTitle:'Who sees this, and when?', note:'<strong>The business owner sees this once during initial onboarding, before payment.</strong> A draft owner can return via “Continue setup.” The salon’s clients never fill out this form.' },
  { key:'checkout', label:'Checkout', sub:'Secure Stripe payment', title:'Review. Pay. Join the setup queue.', status:'Stripe test mode', path:'Stripe Checkout → /account', lead:'Stripe shows the monthly plan and one-time setup charge. After checkout, the owner returns to their dashboard.', actions:['Review the exact setup fee and first payment.','Complete secure payment with Stripe.','See “Payment received” after payment is verified.'], next:'Verified payment moves the business into the setup queue. It does not activate incoming calls.', mock:'<div class="row"><div class="brand">AI Receptionist</div><small>Stripe Checkout</small></div><h4>Your first payment.</h4><div class="status-row"><div>Busy desk · first month</div><strong>$399</strong></div><div class="status-row"><div>Pilot setup · if available</div><strong>$299</strong></div><div class="row" style="margin:21px 0"><div>Illustrative total, before tax</div><div class="price">$698</div></div><small>Then $399/month, plus authorized extra minutes and applicable tax. Standard setup is $499 if pilot pricing is unavailable.</small>'+button('Pay securely')+'<div class="hint">Sandbox today · No live payment activation in this journey.</div>', noteTitle:'Payment is one checkpoint', note:'Returning from Stripe is not proof of payment or a connected phone. The dashboard follows verified payment status; preparation and testing happen next.' },
  { key:'prepare', label:'Connect & test', sub:'Setup with our team', title:'We prepare it with the owner.', status:'Activation required', pending:true, path:'Owner dashboard + assisted setup', lead:'We use their provider details to choose the right connection process, prepare the appointment book, and arrange a test call.', actions:['Confirm the exact phone service and booking system.','Prepare an answering line and the owner’s call preferences.','Test a full call, booking, staff fallback and spending limit.'], next:'Only a tested connection can be marked ready for incoming AI calls.', mock:brand+'<h4>Your front desk<br>is being prepared.</h4><div class="status-row"><div>Business details</div><span>Received</span></div><div class="status-row"><div>Phone provider + service</div><span>Review</span></div><div class="status-row"><div>Appointment book</div><span>Compatibility check</span></div><div class="status-row"><div>AI answering line</div><span class="wait">Needs connection</span></div><div class="status-row"><div>Test call with the owner</div><span class="wait">Before activation</span></div><small style="margin-top:13px">Illustrated setup milestones. Assisted work still required.</small>', noteTitle:'This is the work still ahead', note:'The incoming booking tools and controls exist locally. The real voice adapter, trusted call connection and live pilot acceptance are still pending. An existing booking system will not connect automatically.' },
  { key:'activate', label:'Go live', sub:'After verified setup', title:'Open the right doors.', status:'Activation required', pending:true, path:'Booking page + verified phone connection', lead:'The owner shares their booking page. Incoming AI answering is enabled only after its own phone connection has been verified.', actions:['Share the business’s online booking link.','Test forwarding and the original phone route before switching.','Confirm who answers during open hours, after hours and time away.'], next:'Customers can use the booking page. The phone journey begins once the phone connection is ready.', mock:brand+'<h4>Ready for customers.</h4><div class="selection"><small>ONLINE BOOKING</small><div style="margin:10px 0">Your business booking page ↗</div><small>Available when the customer account is live.</small></div><div class="selection" style="margin-top:12px"><small>INCOMING AI ANSWERING</small><div style="margin:10px 0">Verified phone connection required</div><small>Controlled separately from the booking page.</small></div><div class="hint">Activation example · Both pilot phone connections are still pending.</div>', noteTitle:'Two separate readiness checks', note:'<strong>A live booking page does not mean we are answering the business’s phone.</strong> Carrier forwarding and the AI answering connection must each be set up and tested.' },
  { key:'manage', label:'Manage', sub:'Owner dashboard', title:'Their front desk, at a glance.', status:'Controls built locally', path:'/account', lead:'After setup, the owner returns here to see bookings and call outcomes, change answering preferences and manage spending.', actions:['See appointments, incoming calls and follow-up needs.','Control confirmations, schedules, vacations and temporary changes.','Watch minutes, alerts, spending limits and billing.'], next:'The owner keeps control while customers book online or use a verified answering line.', link:['Open dashboard preview','http://localhost:3102/account'], mock:brand+'<h4>Your front desk.</h4><div class="metrics"><div class="metric">Appointments<b>12</b></div><div class="metric">Minutes used<b>80 / 300</b></div><div class="metric">Extra usage<b>$0</b></div></div><div class="selection"><div class="row"><strong>Your phone, your choice</strong><small>Example settings</small></div><div class="status-row">During business hours <span>Let the caller choose</span></div><div class="status-row">After hours <span>AI answers first</span></div></div><div class="line" style="margin-top:12px">Recent call → Appointment confirmed</div><small>Illustrative data; not a real customer’s activity.</small>', noteTitle:'Returning owners', note:'An owner who has already started checkout or moved beyond draft goes to the dashboard instead of seeing this initial form again. Draft owners without an open checkout can return to setup.' }
];

const online = [
  {key:'find',label:'Open link',sub:'Business booking page',title:'“I need an appointment.”',status:'App flow',path:'/b/{business}',lead:'A customer follows the booking link shared by the business. They do not sign up for AI Receptionist or choose a subscription.',actions:['Open the link from the business’s website or a shared message.','See the business name, services and team.'],next:'Choose the person or service to book.',mock:'<div class="brand">EXAMPLE SALON</div><h4>Make a little time<br>for yourself.</h4><small>Book an appointment with our team.</small><div class="selection" style="margin-top:23px">Jordan · Cut & finish<br><small>45 minutes</small></div><div class="selection" style="margin-top:9px">Alex · Colour consultation<br><small>30 minutes</small></div>',noteTitle:'The business’s customer',note:'This person only needs an appointment. Provider selection, Stripe subscription checkout and answering controls belong to the business owner.'},
  {key:'choose',label:'Choose time',sub:'Real availability',title:'Find a time that works.',status:'App flow',path:'Business booking form',lead:'They select a team member or service, choose a date, and see the currently available appointment times.',actions:['Select the team member and appointment.','Choose a date and an available time.'],next:'Enter contact details and appointment consent.',mock:'<div class="brand">EXAMPLE SALON</div><h4>Cut & finish.</h4><small>Jordan · 45 minutes</small><div class="field" style="margin-top:18px">Tuesday, 15 September &nbsp;⌄</div><div class="times"><span>10:00 AM</span><span>11:30 AM</span><span>2:00 PM</span></div><small>Example times. Actual slots come from the business’s appointment book.</small>'+button('Continue →'),noteTitle:'The appointment book matters',note:'The app checks its own booking calendar. External salon software is not automatically synchronized. Current rules allow bookings with 90 minutes’ notice and up to 30 days ahead.'},
  {key:'details',label:'Reserve',sub:'Details + consent',title:'Put a name to the booking.',status:'App flow',path:'Business booking form',lead:'The customer enters contact details and consent. Saving reserves the appointment if the slot is still available.',actions:['Enter their name and phone number.','Review the appointment and contact consent.','Submit the booking.'],next:'A saved booking opens the customer’s private confirmation page.',mock:'<div class="brand">EXAMPLE SALON</div><h4>Your appointment.</h4>'+field('Full name','Jamie Example')+'<div style="margin-top:12px">'+field('Phone number','Your contact number')+'</div><small style="margin-top:16px">☑ &nbsp; Contact consent, including an AI confirmation call.</small>'+button('Reserve appointment →'),noteTitle:'No owner onboarding',note:'Customers never enter the business’s phone provider or pay for an AI Receptionist plan. They only provide what is needed for their appointment.'},
  {key:'confirmation',label:'Confirmation',sub:'Saved booking + call choice',title:'The booking is saved.',status:'App flow',path:'/b/{business}/confirmation/{booking}',lead:'The confirmation page shows the saved appointment. If the business has enabled outgoing confirmation calls, an AI call is queued about this existing booking.',actions:['Review the appointment details.','Receive a confirmation call if enabled and calling is available.','If calling is off, the business follows up as needed.'],next:'The owner sees the booking and any call result in their dashboard.',mock:'<div class="center"><div class="success">✓</div><div class="brand">EXAMPLE SALON</div><h4>Your appointment<br>is reserved.</h4><small>Jordan · Cut & finish · 45 minutes</small><div class="hint">If confirmation calls are enabled, the AI calls about this existing appointment.</div></div>',noteTitle:'Two different kinds of AI call',note:'An outgoing confirmation call follows an online booking. An incoming AI booking call creates an appointment during the conversation. These are separate features.'},
  {key:'owner',label:'Owner sees it',sub:'Booking + call outcome',title:'One place to follow up.',status:'App flow',path:'Owner dashboard /account',lead:'The business owner sees the appointment, call status and anything that needs their attention.',actions:['Review the booking and confirmation outcome.','Follow up on cancellation or reschedule requests.'],next:'The customer attends their appointment. The owner manages any changes.',mock:brand+'<h4>Appointments.</h4><div class="selection"><div class="row"><strong>Jamie Example</strong><span>Confirmed</span></div><small style="margin-top:10px">Jordan · Cut & finish</small></div><div class="line" style="margin-top:18px">Call outcome and summary appear here.</div><small>Example record. Reschedule and cancellation requests require staff follow-up.</small>',noteTitle:'The two journeys meet here',note:'The customer gets an appointment. The owner gets a booking record and any call outcome in the same account.'}
];

const phone = [
  {key:'dial',label:'Call',sub:'Existing business number',title:'They call the number they know.',status:'Connection required',pending:true,path:'Business phone → answering gateway',lead:'The customer dials the business’s existing number. Configured carrier forwarding or phone routing must bring the call to the answering service.',actions:['Dial the business as usual.','The provider passes the call to the configured destination.'],next:'The owner’s saved answering rules decide what happens next.',mock:'<div class="center"><div class="success">☎</div><div class="brand">CUSTOMER’S PHONE</div><h4>Calling the salon…</h4><small>The existing business number stays familiar.</small><div class="hint">This connection has not been activated for either pilot.</div></div>',noteTitle:'Provider selection is preparation',note:'Knowing Comcast, T-Mobile or another provider helps us choose the connection steps. It does not let the app silently change that provider’s forwarding settings.'},
  {key:'route',label:'Who answers?',sub:'Schedule + owner choice',title:'The business decides.',status:'Controls built; connection pending',pending:true,path:'Menu / staff first / AI first / staff only',lead:'Business hours, holidays and temporary settings choose how the call is handled. A menu is one option, not a requirement.',actions:['Menu: choose AI booking or a person.','Staff first: ring staff, with the chosen fallback.','AI first or staff only: follow the owner’s selection.'],next:'AI booking checks availability. Human requests go to staff or voicemail.',mock:'<div class="brand">EXAMPLE CALL MENU</div><h4>How can we help?</h4><div class="branch"><div><b>Press 1</b>Schedule an appointment</div><div><b>Press 2</b>Speak with someone</div></div><div class="hint">A separate staff destination is required. Without one, the human option takes a message.</div>',noteTitle:'There is always another path',note:'An explicit request for a person goes to staff or voicemail. If the call budget is exhausted, the configured staff/voicemail fallback takes over.'},
  {key:'talk',label:'Find a slot',sub:'AI checks the book',title:'A conversation with a purpose.',status:'Tools built; connection pending',pending:true,path:'AI conversation → appointment availability',lead:'The AI asks what the caller needs, checks the business’s available slots and offers a suitable time.',actions:['Identify the service and team member.','Check actual appointment availability.','Read back the proposed appointment.'],next:'The caller agrees before the appointment is saved.',mock:'<div class="brand">ILLUSTRATIVE CONVERSATION</div><div class="bubble">What would you like to book?</div><div class="bubble reply">A haircut with Jordan, Tuesday morning.</div><div class="bubble">I have 10 AM available. That’s a 45-minute appointment. Would you like me to book it?</div><div class="bubble reply">Yes, please.</div>',noteTitle:'No invented availability',note:'The booking tools use the app’s appointment book. Connecting an existing salon calendar still requires a separate, verified integration.'},
  {key:'book',label:'Book',sub:'Caller agrees → saved',title:'Only say “booked” once it is saved.',status:'Tools built; connection pending',pending:true,path:'Confirmed caller choice → saved appointment',lead:'After the caller agrees, the booking tool saves the appointment. A retry returns the original result, and a taken slot cannot be double-booked.',actions:['Capture the caller’s contact details.','Save the confirmed appointment.','Explain the result clearly to the caller.'],next:'The booking and call outcome appear in the owner’s account.',mock:'<div class="center"><div class="success">✓</div><h4>“You’re booked for<br>Tuesday at 10.”</h4><small>Only after the booking tool confirms the appointment was saved.</small></div><div class="hint">No immediate duplicate outgoing confirmation call for a booking already confirmed on the phone.</div>',noteTitle:'The moment of truth',note:'A conversation alone is not a booking. The saved appointment is the confirmation, and another caller must not be able to take the same slot.'},
  {key:'record',label:'Owner sees it',sub:'Call + booking + minutes',title:'The owner stays in the loop.',status:'Records built locally',path:'Incoming calls + appointments + usage',lead:'The owner sees the incoming call, its outcome, any saved booking and the AI minutes used. Calls without a booking are recorded too.',actions:['Review the call summary and appointment.','Follow up when a caller needs a person.','See shared plan usage and spending alerts.'],next:'The owner manages their front desk from the dashboard.',mock:brand+'<h4>Incoming calls.</h4><div class="selection"><strong>Appointment booked</strong><small style="margin-top:8px">Jamie · Cut & finish with Jordan</small></div><div class="status-row">Call summary <span>Available after report</span></div><div class="status-row">AI minutes <span>Shared plan allowance</span></div><div class="progress"></div><small>Illustrative record. Actual email delivery still requires setup.</small>',noteTitle:'The two journeys meet here',note:'The customer makes a familiar phone call. The owner gets a recorded outcome, appointment and usage record after the verified phone integration is running.'}
];

let audience = 'owner';
let channel = 'online';
let selected = 2;
const timeline = document.querySelector('#timeline');
const detail = document.querySelector('#detail');
function steps(){return audience === 'owner' ? owner : channel === 'phone' ? phone : online;}
function render(){
  const list = steps(), entry = list[selected];
  document.querySelectorAll('[data-audience]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.audience===audience)));
  document.querySelectorAll('[data-channel]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.channel===channel)));
  document.querySelector('#channel').hidden = audience === 'owner';
  document.querySelector('#context').textContent = audience === 'owner' ? 'The person paying for AI Receptionist.' : 'The person booking with that business. No AI Receptionist signup.';
  document.querySelector('#route-title').textContent = audience === 'owner' ? 'Becoming an AI Receptionist customer' : channel === 'online' ? 'Booking an appointment online' : 'Booking by phone · connection still required';
  timeline.style.setProperty('--count',list.length);
  timeline.innerHTML = list.map((s,i)=>`<li><button class="step" data-step="${i}" ${i===selected?'aria-current="step"':''} aria-label="Step ${i+1}: ${s.label}${audience==='owner'&&i===2?', the current setup screen':''}"><div class="step-top"><span class="step-number">${String(i+1).padStart(2,'0')}</span>${audience==='owner'&&i===2?'<span class="you">This screen</span>':s.pending?'<span class="step-number">○</span>':''}</div><span class="step-name">${s.label}</span><span class="step-sub">${s.sub}</span></button></li>`).join('');
  detail.innerHTML = `<div class="explain"><div class="detail-kicker">Step ${String(selected+1).padStart(2,'0')} <span class="pill ${entry.pending?'pending':''}">${entry.status}</span></div><h3>${entry.title}</h3><p class="lead">${entry.lead}</p><div class="action-title">What happens</div><ul class="actions">${entry.actions.map(a=>`<li>${a}</li>`).join('')}</ul><div class="transition"><span>Then what?</span><strong>${entry.next}</strong></div>${entry.link?`<a class="next-link" href="${entry.link[1]}" target="_blank" rel="noopener">${entry.link[0]} ↗</a>`:''}</div><div class="screen-area"><div class="screen-label"><span>${audience==='owner'?'What the owner sees':'The customer experience'}</span><span>${entry.path}</span></div>${screen(entry.mock)}</div>`;
  document.querySelector('#note-title').textContent=entry.noteTitle;
  document.querySelector('#note-copy').innerHTML=entry.note;
  document.querySelector('#position').textContent=`${selected+1} of ${list.length} · ${audience==='owner'?'Business owner':channel==='phone'?'Customer calling':'Customer booking online'}`;
  document.querySelector('#prev').disabled=selected===0;
  document.querySelector('#next').disabled=selected===list.length-1;
  // A fragment-only URL would resolve against the preview's injected <base>.
  const selectedUrl = new URL(location.href);
  selectedUrl.hash = `${audience==='owner'?'owner':channel}-${entry.key}`;
  history.replaceState(null,'',selectedUrl.href);
}
document.querySelectorAll('[data-audience]').forEach(el=>el.addEventListener('click',()=>{audience=el.dataset.audience;selected=audience==='owner'?2:0;render();}));
document.querySelectorAll('[data-channel]').forEach(el=>el.addEventListener('click',()=>{channel=el.dataset.channel;selected=0;render();}));
timeline.addEventListener('click',event=>{const button=event.target.closest('[data-step]');if(!button)return;selected=Number(button.dataset.step);render();timeline.querySelector(`[data-step="${selected}"]`).focus({preventScroll:true});});
document.querySelector('#prev').addEventListener('click',()=>{if(selected>0){selected--;render();}});
document.querySelector('#next').addEventListener('click',()=>{if(selected<steps().length-1){selected++;render();}});
function readHash(){
  const match=/^#(owner|online|phone)-([a-z]+)$/.exec(location.hash);
  if(match){audience=match[1]==='owner'?'owner':'customer';channel=match[1]==='phone'?'phone':'online';const index=steps().findIndex(s=>s.key===match[2]);selected=index>=0?index:0;}
  render();
}
window.addEventListener('hashchange',readHash);
readHash();
