import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL??'http://127.0.0.1:3101';
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const width of [320,375,768,1024,1440,1920]){await page.setViewportSize({width,height:900});await page.goto(`${base}/account/settings?preview=settings`);await page.getByRole('button',{name:'Save business settings'}).waitFor();await page.getByRole('link',{name:'Hours & availability',exact:true}).last().click();const metrics=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,scrollers:[...document.querySelectorAll('[class*="scroller"]')].map(e=>({client:e.clientWidth,scroll:e.scrollWidth})),font:getComputedStyle(document.querySelector('[aria-label="Monday opens"]')).fontSize}));assert.equal(metrics.overflow,false);metrics.scrollers.forEach(e=>assert.ok(e.scroll<=e.client+1));console.log(width,metrics);if([320,1440].includes(width))await page.screenshot({path:`/tmp/settings-${width}.png`});}
await page.setViewportSize({width:375,height:812});await page.getByLabel('Business name',{exact:true}).fill('Updated Studio');await page.getByRole('slider',{name:'Monday opening time'}).focus();await page.keyboard.press('ArrowDown');await page.waitForFunction(()=>document.querySelector('[aria-label="Monday opens"]').value==='9:15 AM');await page.getByLabel('Tuesday opens',{exact:true}).fill('10:30 AM');await page.getByLabel('Tuesday opens',{exact:true}).press('Tab');await page.getByRole('button',{name:'Wednesday all day'}).click();await page.getByLabel('Friday open',{exact:true}).uncheck();await page.getByRole('button',{name:'Save business settings'}).click();await page.getByText('Saved on this device. Your setup preview uses these details too.').waitFor();await page.reload();await page.getByRole('button',{name:'Save business settings'}).waitFor();assert.equal(await page.getByLabel('Business name',{exact:true}).inputValue(),'Updated Studio');assert.equal(await page.getByLabel('Tuesday opens',{exact:true}).inputValue(),'10:30 AM');assert.equal(await page.getByLabel('Friday open',{exact:true}).isChecked(),false);
await page.goto(`${base}/account?preview=confirmation`);await page.waitForSelector('#review-setup');assert.equal(await page.locator('input[name="business_name"]').inputValue(),'Updated Studio');assert.equal(await page.getByLabel('Tuesday opens',{exact:true}).inputValue(),'10:30 AM');await page.locator('input[name="business_name"]').fill('Autosaved Studio');await page.waitForTimeout(900);await page.reload();await page.waitForSelector('#review-setup');assert.equal(await page.locator('input[name="business_name"]').inputValue(),'Autosaved Studio');
await page.setViewportSize({width:667,height:375});await page.waitForTimeout(150);await page.getByRole('button',{name:'Choose monday opens',exact:true}).click();await page.getByRole('listbox',{name:'Monday opens'}).waitFor();await page.waitForTimeout(100);const menu=await page.getByRole('listbox',{name:'Monday opens'}).boundingBox();assert.ok(menu&&menu.x>=0&&menu.x+menu.width<=667&&menu.y+menu.height<=375);await page.keyboard.press('Escape');
for(const width of [320,768,1440]){await page.setViewportSize({width,height:800});await page.goto(`${base}/start`);await page.waitForLoadState('networkidle');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);console.log('start fits',width);}
console.log('PASS persistence, keyboard/manual/all-day/closed schedule, setup continuity, autosave, signup; errors:',errors);assert.deepEqual(errors,[]);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
