/**
 * Renders supabase/seed.sql from each vertical's roster so the two never
 * drift. Roster modules carry only type imports, which Node strips, so this
 * runs with no build step:  npm run seed:sql
 */
import { writeFileSync } from "node:fs";
import { ROSTERS } from "../src/verticals/rosters.ts";

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const arr = (v: (string | number)[]) => `'{${v.map(String).join(",")}}'`;

const rows = ROSTERS.flat().map((p) =>
  [
    "(",
    `  ${q(p.id)}, ${q(p.vertical)}, ${q(p.slug)}, ${q(p.name)}, ${q(p.credentials)}, ${q(p.specialty)},`,
    `  ${q(p.bio)},`,
    `  ${q(p.photo_url)},`,
    `  ${p.years_experience}, ${p.rating}, ${p.reviews_count}, ${arr(p.languages)}, ${q(p.education)},`,
    `  ${p.consultation_fee}, ${q(p.location)}, ${arr(p.working_days)}, ${q(p.start_time)}, ${q(p.end_time)}, ${p.slot_minutes}, ${p.is_active}`,
    ")",
  ].join("\n"),
);

const COLUMNS = [
  "id", "vertical", "slug", "name", "credentials", "specialty", "bio", "photo_url",
  "years_experience", "rating", "reviews_count", "languages", "education",
  "consultation_fee", "location", "working_days", "start_time", "end_time", "slot_minutes", "is_active",
];

const sql = `-- ============================================================================
-- AI Receptionist — provider roster seed
-- GENERATED by scripts/generate-seed-sql.ts from src/verticals/*/roster.ts.
-- Do not edit by hand; run \`npm run seed:sql\`.
-- Run after schema.sql. Safe to re-run: rows are upserted by (vertical, slug).
-- ============================================================================

insert into public.providers (
  ${COLUMNS.join(", ")}
) values
${rows.join(",\n")}
on conflict (vertical, slug) do update set
${COLUMNS.filter((c) => !["id", "vertical", "slug"].includes(c)).map((c) => `  ${c.padEnd(16)} = excluded.${c}`).join(",\n")};
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`wrote supabase/seed.sql — ${rows.length} providers`);
