import type { Provider } from "@/lib/types";

const photo = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&crop=faces&w=640&h=640&q=80`;

/**
 * The salon's team. Serves the demo directly and feeds `npm run seed:sql`,
 * so it must stay free of runtime imports (type-only is fine).
 */
const ROSTER: Omit<Provider, "vertical">[] = [
  {
    id: "11111111-1111-4111-8111-111111110201",
    slug: "sasha-reyes",
    name: "Sasha Reyes",
    credentials: "Master Colourist",
    specialty: "Colour",
    bio: "Sasha has spent twelve years doing the colour other salons send people to her to fix. Balayage, lived-in blondes, and corrective work — she'll tell you honestly what your hair can take in one sitting and what it can't.",
    photo_url: photo("photo-1494790108377-be9c29b29330"),
    years_experience: 12,
    rating: 4.9,
    reviews_count: 388,
    languages: ["English", "Spanish"],
    education: "Vidal Sassoon Academy · Wella Master Colour Expert",
    consultation_fee: 145,
    location: "Colour bar · Ground floor",
    working_days: [2, 3, 4, 5, 6],
    start_time: "09:00",
    end_time: "18:00",
    slot_minutes: 90,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110202",
    slug: "theo-lindqvist",
    name: "Theo Lindqvist",
    credentials: "Senior Stylist",
    specialty: "Cutting & styling",
    bio: "Precision cuts and the kind of blowout that survives a commute. Theo trained in London and still cuts dry first, because that's how you actually wear it.",
    photo_url: photo("photo-1507003211169-0a1dd7228f2d"),
    years_experience: 9,
    rating: 4.8,
    reviews_count: 302,
    languages: ["English", "Swedish"],
    education: "Toni&Guy Academy, London",
    consultation_fee: 85,
    location: "Main floor",
    working_days: [1, 2, 3, 4, 5],
    start_time: "10:00",
    end_time: "19:00",
    slot_minutes: 60,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110203",
    slug: "marcus-oyelaran",
    name: "Marcus Oyelaran",
    credentials: "Barber",
    specialty: "Barbering",
    bio: "Fades, scissor cuts, hot-towel shaves and beard shaping. Marcus keeps a chair free most days for walk-ins, but regulars book — his Saturdays go a week out.",
    photo_url: photo("photo-1500648767791-00dcc994a43e"),
    years_experience: 7,
    rating: 4.9,
    reviews_count: 411,
    languages: ["English"],
    education: "Apprenticed at Ruffians, Edinburgh",
    consultation_fee: 45,
    location: "Barber chairs · Ground floor",
    working_days: [1, 2, 3, 5, 6],
    start_time: "09:00",
    end_time: "17:00",
    slot_minutes: 30,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110204",
    slug: "lina-farouk",
    name: "Lina Farouk",
    credentials: "Licensed Esthetician",
    specialty: "Skin & facials",
    bio: "Results-led facials, peels and LED, with a soft spot for skin that's been overdone by too many products. Lina starts every first visit with a proper skin analysis before touching anything.",
    photo_url: photo("photo-1438761681033-6461ffad8d80"),
    years_experience: 10,
    rating: 5.0,
    reviews_count: 276,
    languages: ["English", "Arabic", "French"],
    education: "CIDESCO diploma · Dermalogica Expert",
    consultation_fee: 110,
    location: "Treatment rooms · First floor",
    working_days: [2, 3, 4, 5, 6],
    start_time: "10:00",
    end_time: "18:00",
    slot_minutes: 60,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110205",
    slug: "priya-nair",
    name: "Priya Nair",
    credentials: "Massage Therapist",
    specialty: "Massage",
    bio: "Deep tissue, sports and prenatal massage. Priya trained in Thai massage in Chiang Mai and will absolutely find the knot you've been ignoring since March.",
    photo_url: photo("photo-1544005313-94ddf0286df2"),
    years_experience: 11,
    rating: 4.9,
    reviews_count: 349,
    languages: ["English", "Hindi"],
    education: "CAMTC certified · Thai massage, Chiang Mai",
    consultation_fee: 120,
    location: "Spa suite · First floor",
    working_days: [1, 3, 4, 5, 6],
    start_time: "10:00",
    end_time: "19:00",
    slot_minutes: 60,
    is_active: true,
  },
  {
    id: "11111111-1111-4111-8111-111111110206",
    slug: "jonah-park",
    name: "Jonah Park",
    credentials: "Stylist",
    specialty: "Cutting & styling",
    bio: "Textured cuts, curls and the occasional brave fringe. Jonah is the one to book if you have a photo on your phone and aren't sure it'll work — he'll tell you, kindly.",
    photo_url: photo("photo-1506794778202-cad84cf45f1d"),
    years_experience: 5,
    rating: 4.7,
    reviews_count: 188,
    languages: ["English", "Korean"],
    education: "Aveda Institute",
    consultation_fee: 70,
    location: "Main floor",
    working_days: [1, 2, 4, 5, 6],
    start_time: "11:00",
    end_time: "20:00",
    slot_minutes: 45,
    is_active: true,
  },
];

export const SALON_ROSTER: Provider[] = ROSTER.map((p) => ({ ...p, vertical: "salon" }));
