import type { Appointment, CallLog, Client } from "@/lib/types";
import { DAY, iso, slotFor } from "../seed-utils";
import { SALON_ROSTER as R } from "./roster";

/** Tier C: the guests, bookings and transcripts that make the salon's dashboard look lived-in. */
export function buildSalonSeed(now: number) {
  const clients: Client[] = [
    {
      id: "22222222-2222-4222-8222-222222220201",
      full_name: "Jade Okafor",
      phone: "+1 415 555 0198",
      email: "jade.okafor@example.com",
      notes: null,
      created_at: iso(now - 5 * DAY),
    },
    {
      id: "22222222-2222-4222-8222-222222220202",
      full_name: "Daniel Whitfield",
      phone: "+1 415 555 0163",
      email: "d.whitfield@example.com",
      notes: null,
      created_at: iso(now - 3 * DAY),
    },
    {
      id: "22222222-2222-4222-8222-222222220203",
      full_name: "Amara Osei",
      phone: "+1 415 555 0127",
      email: "amara.osei@example.com",
      notes: null,
      created_at: iso(now - 2 * DAY),
    },
    {
      id: "22222222-2222-4222-8222-222222220204",
      full_name: "Felix Brandt",
      phone: "+1 415 555 0181",
      email: null,
      notes: null,
      created_at: iso(now - 1 * DAY),
    },
  ];

  const appointments: Appointment[] = [
    {
      id: "33333333-3333-4333-8333-333333330201",
      vertical: "salon",
      reference: "SS-4HK2MW",
      provider_id: R[0].id,
      client_id: clients[0].id,
      ...slotFor(R[0], 2, 14, 0),
      reason: "Balayage refresh and a trim.",
      status: "confirmed",
      is_new_client: false,
      created_at: iso(now - 5 * DAY),
      updated_at: iso(now - 5 * DAY + 80_000),
    },
    {
      id: "33333333-3333-4333-8333-333333330202",
      vertical: "salon",
      reference: "SS-8RT5QA",
      provider_id: R[2].id,
      client_id: clients[1].id,
      ...slotFor(R[2], 3, 10, 30),
      reason: "Skin fade and beard tidy.",
      status: "confirmed",
      is_new_client: true,
      created_at: iso(now - 3 * DAY),
      updated_at: iso(now - 3 * DAY + 95_000),
    },
    {
      id: "33333333-3333-4333-8333-333333330203",
      vertical: "salon",
      reference: "SS-2PN9DX",
      provider_id: R[3].id,
      client_id: clients[2].id,
      ...slotFor(R[3], 1, 11, 0),
      reason: "First facial — skin's been reactive lately.",
      status: "rescheduled",
      is_new_client: true,
      created_at: iso(now - 2 * DAY),
      updated_at: iso(now - 2 * DAY + 180_000),
    },
    {
      id: "33333333-3333-4333-8333-333333330204",
      vertical: "salon",
      reference: "SS-6WB3LC",
      provider_id: R[4].id,
      client_id: clients[3].id,
      ...slotFor(R[4], 4, 17, 0),
      reason: "Deep tissue, lower back.",
      // Matches its call log: the assistant rang and nobody picked up.
      status: "no_answer",
      is_new_client: false,
      created_at: iso(now - 1 * DAY),
      updated_at: iso(now - 1 * DAY),
    },
  ];

  const calls: CallLog[] = [
    {
      id: "44444444-4444-4444-8444-444444440201",
      appointment_id: appointments[0].id,
      client_id: clients[0].id,
      provider: "demo",
      kind: "confirmation",
      demo_phone: null,
      demo_business: null,
      demo_name: null,
      reference: null,
      provider_call_id: "demo_call_4HK2MW",
      direction: "outbound",
      status: "completed",
      outcome: "confirmed",
      recording_url: "/audio/sample-call.wav",
      transcript: [
        "Agent: Hi, this is Robin calling from Solstice Salon & Spa. Am I speaking with Jade Okafor?",
        "Jade: Yes, hi!",
        "Agent: Lovely. I'm confirming your balayage refresh and trim with Sasha. Does that time still work for you?",
        "Jade: It does.",
        "Agent: Perfect, you're confirmed. Come in five minutes early and we'll get you settled. Anything else I can help with?",
        "Jade: No, that's everything. Thanks!",
        "Agent: See you then, Jade.",
      ].join("\n"),
      summary:
        "Guest confirmed the appointment. No changes requested. Reminded to arrive five minutes early.",
      duration_seconds: 41,
      cost: 0.1,
      error: null,
      started_at: iso(now - 5 * DAY + 28_000),
      ended_at: iso(now - 5 * DAY + 69_000),
      created_at: iso(now - 5 * DAY + 5_000),
    },
    {
      id: "44444444-4444-4444-8444-444444440202",
      appointment_id: appointments[1].id,
      client_id: clients[1].id,
      provider: "demo",
      kind: "confirmation",
      demo_phone: null,
      demo_business: null,
      demo_name: null,
      reference: null,
      provider_call_id: "demo_call_8RT5QA",
      direction: "outbound",
      status: "completed",
      outcome: "confirmed",
      recording_url: "/audio/sample-call.wav",
      transcript: [
        "Agent: Good afternoon, this is Robin from Solstice Salon & Spa calling for Daniel Whitfield.",
        "Daniel: Speaking.",
        "Agent: I'm confirming your skin fade and beard tidy with Marcus. I also see it's your first visit with us — is that right?",
        "Daniel: First time, yeah.",
        "Agent: Great, I'll text you a short consultation form. Shall I keep the appointment as scheduled?",
        "Daniel: Yes, keep it.",
        "Agent: You're all set. Thanks, Daniel.",
      ].join("\n"),
      summary:
        "Confirmed. New guest — consultation form to be texted. No changes requested.",
      duration_seconds: 52,
      cost: 0.13,
      error: null,
      started_at: iso(now - 3 * DAY + 36_000),
      ended_at: iso(now - 3 * DAY + 88_000),
      created_at: iso(now - 3 * DAY + 6_000),
    },
    {
      id: "44444444-4444-4444-8444-444444440203",
      appointment_id: appointments[2].id,
      client_id: clients[2].id,
      provider: "demo",
      kind: "confirmation",
      demo_phone: null,
      demo_business: null,
      demo_name: null,
      reference: null,
      provider_call_id: "demo_call_2PN9DX",
      direction: "outbound",
      status: "completed",
      outcome: "rescheduled",
      recording_url: "/audio/sample-call.wav",
      transcript: [
        "Agent: Hello, this is Robin at Solstice Salon & Spa, calling for Amara Osei.",
        "Amara: Hi — yes, but I've just realised I can't make that morning.",
        "Agent: No problem at all. Lina has space later that afternoon or the following morning. Would either suit?",
        "Amara: The following morning would be better.",
        "Agent: I've noted that, and the front desk will text you a new time to confirm within the hour.",
        "Amara: Perfect, thank you.",
      ].join("\n"),
      summary:
        "Guest cannot attend the booked slot. Requested the following morning. Flagged for front-desk rebooking.",
      duration_seconds: 48,
      cost: 0.12,
      error: null,
      started_at: iso(now - 2 * DAY + 33_000),
      ended_at: iso(now - 2 * DAY + 81_000),
      created_at: iso(now - 2 * DAY + 4_000),
    },
    {
      id: "44444444-4444-4444-8444-444444440204",
      appointment_id: appointments[3].id,
      client_id: clients[3].id,
      provider: "demo",
      kind: "confirmation",
      demo_phone: null,
      demo_business: null,
      demo_name: null,
      reference: null,
      provider_call_id: "demo_call_6WB3LC",
      direction: "outbound",
      status: "completed",
      outcome: "no_answer",
      recording_url: null,
      transcript: null,
      summary: "No answer after four rings. Voicemail was not available. Retry queued.",
      duration_seconds: 19,
      cost: 0.03,
      error: null,
      started_at: iso(now - 1 * DAY + 30_000),
      ended_at: iso(now - 1 * DAY + 49_000),
      created_at: iso(now - 1 * DAY + 3_000),
    },
  ];

  return { clients, appointments, calls };
}
